# Generated by Django 4.0.2 on 2022-02-09 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='atricle_text',
            new_name='article_text',
        ),
    ]
